[relaychain]
default_command = "./bin/infrablockspace"
default_args = ["-lparachain=trace", "-lxcm=trace"]
chain = "infrablockspace-local"

[[relaychain.nodes]]
name = "alice"
ws_port = 9700
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[relaychain.nodes]]
name = "charlie"
validator = true

[[parachains]]
id = 1001
chain = "collectives-infrablockspace-local"
cumulus_based = true

[[parachains.collators]]
name = "collator1"
ws_port = 9710
command = "./bin/infrablockspace-parachain"
args = ["-lxcm=trace"]

[[parachains.collators]]
name = "collator2"
command = "./bin/infrablockspace-parachain"
args = ["-lxcm=trace"]
