[relaychain]
default_command = "./bin/infrablockspace"
default_args = ["-lparachain=debug"]
chain = "kusama-local"

[[relaychain.nodes]]
name = "alice"
ws_port = 9900
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[relaychain.nodes]]
name = "charlie"
validator = true

[[relaychain.nodes]]
name = "dave"
validator = true

[[parachains]]
id = 1000
chain = "statemine-local"
cumulus_based = true

[[parachains.collators]]
name = "collator1"
ws_port = 9910
command = "./bin/infrablockspace-parachain"

[[parachains.collators]]
name = "collator2"
command = "./bin/infrablockspace-parachain"

[[parachains]]
id = 2000
chain = "penpal-kusama-2000"
cumulus_based = true

[[parachains.collators]]
name = "collator3"
ws_port = 9920
command = "./bin/infrablockspace-parachain"

[[parachains.collators]]
name = "collator4"
command = "./bin/infrablockspace-parachain"
