(function() {var implementors = {
"bridge_hub_infrablockspace_runtime":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"bridge_hub_infrablockspace_runtime/struct.Runtime.html\" title=\"struct bridge_hub_infrablockspace_runtime::Runtime\">Runtime</a>"]],
"bridge_hub_kusama_runtime":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"bridge_hub_kusama_runtime/struct.Runtime.html\" title=\"struct bridge_hub_kusama_runtime::Runtime\">Runtime</a>"]],
"bridge_hub_rococo_runtime":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"bridge_hub_rococo_runtime/struct.Runtime.html\" title=\"struct bridge_hub_rococo_runtime::Runtime\">Runtime</a>"]],
"collectives_infrablockspace_runtime":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"collectives_infrablockspace_runtime/enum.ProxyType.html\" title=\"enum collectives_infrablockspace_runtime::ProxyType\">ProxyType</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"collectives_infrablockspace_runtime/struct.Runtime.html\" title=\"struct collectives_infrablockspace_runtime::Runtime\">Runtime</a>"]],
"contracts_rococo_runtime":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"contracts_rococo_runtime/struct.Runtime.html\" title=\"struct contracts_rococo_runtime::Runtime\">Runtime</a>"]],
"cumulus_client_pov_recovery":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"cumulus_client_pov_recovery/struct.RecoveryDelayRange.html\" title=\"struct cumulus_client_pov_recovery::RecoveryDelayRange\">RecoveryDelayRange</a>"]],
"cumulus_pallet_dmp_queue":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"cumulus_pallet_dmp_queue/struct.ConfigData.html\" title=\"struct cumulus_pallet_dmp_queue::ConfigData\">ConfigData</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"cumulus_pallet_dmp_queue/struct.PageIndexData.html\" title=\"struct cumulus_pallet_dmp_queue::PageIndexData\">PageIndexData</a>"]],
"cumulus_pallet_xcmp_queue":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"cumulus_pallet_xcmp_queue/enum.InboundState.html\" title=\"enum cumulus_pallet_xcmp_queue::InboundState\">InboundState</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"cumulus_pallet_xcmp_queue/enum.OutboundState.html\" title=\"enum cumulus_pallet_xcmp_queue::OutboundState\">OutboundState</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"cumulus_pallet_xcmp_queue/struct.QueueConfigData.html\" title=\"struct cumulus_pallet_xcmp_queue::QueueConfigData\">QueueConfigData</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"cumulus_pallet_xcmp_queue/enum.ChannelSignal.html\" title=\"enum cumulus_pallet_xcmp_queue::ChannelSignal\">ChannelSignal</a>"]],
"cumulus_primitives_core":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"cumulus_primitives_core/enum.MessageSendError.html\" title=\"enum cumulus_primitives_core::MessageSendError\">MessageSendError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"cumulus_primitives_core/enum.ServiceQuality.html\" title=\"enum cumulus_primitives_core::ServiceQuality\">ServiceQuality</a>"]],
"cumulus_test_runtime":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"cumulus_test_runtime/struct.Runtime.html\" title=\"struct cumulus_test_runtime::Runtime\">Runtime</a>"]],
"parachain_template_runtime":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"parachain_template_runtime/struct.Runtime.html\" title=\"struct parachain_template_runtime::Runtime\">Runtime</a>"]],
"penpal_runtime":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"penpal_runtime/struct.Runtime.html\" title=\"struct penpal_runtime::Runtime\">Runtime</a>"]],
"rococo_parachain_runtime":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"rococo_parachain_runtime/struct.Runtime.html\" title=\"struct rococo_parachain_runtime::Runtime\">Runtime</a>"]],
"seedling_runtime":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"seedling_runtime/struct.Runtime.html\" title=\"struct seedling_runtime::Runtime\">Runtime</a>"]],
"shell_runtime":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"shell_runtime/struct.Runtime.html\" title=\"struct shell_runtime::Runtime\">Runtime</a>"]],
"statemine_runtime":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"statemine_runtime/enum.ProxyType.html\" title=\"enum statemine_runtime::ProxyType\">ProxyType</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"statemine_runtime/struct.Runtime.html\" title=\"struct statemine_runtime::Runtime\">Runtime</a>"]],
"statemint_runtime":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"statemint_runtime/enum.ProxyType.html\" title=\"enum statemint_runtime::ProxyType\">ProxyType</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.1/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"statemint_runtime/struct.Runtime.html\" title=\"struct statemint_runtime::Runtime\">Runtime</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()