(function() {var implementors = {
"bridge_hub_infrablockspace_runtime":[["impl Config for <a class=\"struct\" href=\"bridge_hub_infrablockspace_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct bridge_hub_infrablockspace_runtime::xcm_config::XcmConfig\">XcmConfig</a>"]],
"bridge_hub_kusama_runtime":[["impl Config for <a class=\"struct\" href=\"bridge_hub_kusama_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct bridge_hub_kusama_runtime::xcm_config::XcmConfig\">XcmConfig</a>"]],
"bridge_hub_rococo_runtime":[["impl Config for <a class=\"struct\" href=\"bridge_hub_rococo_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct bridge_hub_rococo_runtime::xcm_config::XcmConfig\">XcmConfig</a>"]],
"collectives_infrablockspace_runtime":[["impl Config for <a class=\"struct\" href=\"collectives_infrablockspace_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct collectives_infrablockspace_runtime::xcm_config::XcmConfig\">XcmConfig</a>"]],
"parachain_template_runtime":[["impl Config for <a class=\"struct\" href=\"parachain_template_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct parachain_template_runtime::xcm_config::XcmConfig\">XcmConfig</a>"]],
"penpal_runtime":[["impl Config for <a class=\"struct\" href=\"penpal_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct penpal_runtime::xcm_config::XcmConfig\">XcmConfig</a>"]],
"rococo_parachain_runtime":[["impl Config for <a class=\"struct\" href=\"rococo_parachain_runtime/struct.XcmConfig.html\" title=\"struct rococo_parachain_runtime::XcmConfig\">XcmConfig</a>"]],
"shell_runtime":[["impl Config for <a class=\"struct\" href=\"shell_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct shell_runtime::xcm_config::XcmConfig\">XcmConfig</a>"]],
"statemine_runtime":[["impl Config for <a class=\"struct\" href=\"statemine_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct statemine_runtime::xcm_config::XcmConfig\">XcmConfig</a>"]],
"statemint_runtime":[["impl Config for <a class=\"struct\" href=\"statemint_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct statemint_runtime::xcm_config::XcmConfig\">XcmConfig</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()