[relaychain]
default_command = "../infra-relay-chain/target/release/polkadot"
default_args = ["-lparachain=debug"]
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
rpc_port = 7100
ws_port = 7101

[[relaychain.nodes]]
name = "bob"
validator = true
rpc_port = 7200
ws_port = 7201

[[relaychain.nodes]]
name = "charlie"
validator = true
rpc_port = 7300
ws_port = 7301

[[relaychain.nodes]]
name = "dave"
validator = true
rpc_port = 7400
ws_port = 7401

[[relaychain.nodes]]
name = "eve"
validator = true
rpc_port = 7500
ws_port = 7501

[[parachains]]
id = 1000
chain = "infra-asset-system-local"
cumulus_based = true

# run alice as parachain collator
[[parachains.collators]]
name = "alice"
validator = true
command = "./target/release/infrablockspace-parachain"
args = ["-lparachain=debug"]
rpc_port = 9500
ws_port = 9501

# [[parachains]]
# id = 2000
# chain = "local"
# cumulus_based = true

# # run bob as parachain collator
# [[parachains.collators]]
# name = "bob"
# validator = true
# command = "./target/release/parachain-template-node"
# args = ["-lparachain=debug"]
# rpc_port = 9600
# ws_port = 9601