[relaychain]
default_command = "../infrablockspace/target/release/polkadot"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 1001
chain = "local"
cumulus_based = true

	# run alice as parachain collator
	[[parachains.collators]]
	name = "alice"
	validator = true
	command = "./target/release/parachain-template-node"
	args = ["-lparachain=debug", "--alice"]