[relaychain]
default_image = "parity/infrablockspace:latest"
default_command = "infrablockspace"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 2000
cumulus_based = true
chain = "statemine-local"

# run charlie as parachain collator
[[parachains.collators]]
name = "charlie"
validator = true
image = "parity/infrablockspace-parachain:latest"
command = "infrablockspace-parachain"
args = ["--force-authoring"]
